implement script and governance
cardano-foundation/cf-ls-sync-data-verification pull request #3
Opened 2024-08-28 03:00 UTC by jacklesotatek

2024-08-28 08:00 UTC, obstar requested changes

2024-08-28 08:00 UTC, obstar commented on playwright-database-testing/common/helpers/database/database.helper.ts
`   try {
      await this.init();
      const result: QueryResult<any> = await this.client.query("SELECT script_hash FROM redeemer");
      const scriptHash: string | null = result.rows[0].max;
      return scriptHash;
    } finally {
      await this.teardown();
    }`
that part is common for all functions findScriptHashInRedeemer(), getDelegationVote()...getVottingProcedure()etc.. Please make a helper functions which will take in as argument the query you wanna select from, well you can even pass the whole query as input e.g. something like
`async findScriptHashInRedeemer(): Promise<string | null> { returnQueryResultString("SELECT script_hash FROM redeemer")  } `
  
  `async getDelegationVote(): Promise<object | null> { returnQueryResultObject("SELECT * FROM delegation_vote")}`

I guess it would to helper functions one to return object the other string

2024-08-28 08:19 UTC, jacklesotatek commented on playwright-database-testing/common/helpers/database/database.helper.ts
hi @obstar that is a excellent suggestion
I have update the code according to your suggestion 
please help to re-review again

2024-08-29 06:57 UTC, obstar approved these changes

2024-08-29 07:10 UTC, merged